### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by AndreaMerlin** [hypery2k/cordova-barcodescanner-plugin#16]
Hi,
when I try to install i get this error: 

Fetching plugin "phonegap-plugin-barcodescanner@phonegap-plugin-barcodescanner" via npm
Error: Failed to fetch plugin phonegap-plugin-barcodescanner@phonegap-plugin-barcodescanner via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: No compatible version found: phonegap-plugin-barcodescanner@'phonegap-plugin-barcodescanner'
Valid install targets:
["3.0.0","3.0.1","3.1.0","3.1.1","3.1.2","4.0.0","4.0.1","4.0.2","4.1.0","5.0.0","5.0.1","6.0.0","6.0.1","6.0.2",
"6.0.3","6.0.4","6.0.5"]

I have cordova version 6.5.0. Is not possibile install this plugin? 

Thanks

**Comment by hypery2k** [comment]
you should use the correct plugin: **cordova-plugin-barcodescanner**, [see](https://github.com/hypery2k/cordova-barcodescanner-plugin#installation)

**Comment by amerlin** [comment]
Thanks! Work fine.
