### ISSUE TITLE
Issue with camera on Android 6.1 

### ISSUE THREAD

**Issue by akashs1706** [hypery2k/cordova-barcodescanner-plugin#19]
I am using this plugin to for scanner, but while testing the app in Android 6.1 it displays an error "Sorry, the camera encountered a problem. You may need to restart the device". How can i overcome this issue.

**Comment by bpocallaghan** [comment]
Hi Akash - I am having the same issue.
I've also tried a few different barcode scanners - no luck.

Below are screenshots of the device's software info and the error message.

[Software Info](https://cloud.githubusercontent.com/assets/883465/23152179/e4137554-f808-11e6-9694-0522ae98ac8c.jpeg)
[Error Modal](https://cloud.githubusercontent.com/assets/883465/23152182/e7e886b0-f808-11e6-9bb9-94fd005f7296.jpeg)

If you set your target SDK Version to 22 - it should work.
Unfortunately I've already uploaded the app for 23 - and Google Store does not allow to downgrade the SDK version... <preference name="android-targetSdkVersion" value="22" />

**Comment by akashs1706** [comment]
Thanks @bpocallaghan for the reply.
I have tried for that also but no luck.
I am wondering if there is another solution?

If there is any hack for camera permissions before scanner opens?

**Comment by bpocallaghan** [comment]
Do you mean that you tried setting it to target sdk = 22 without any success?

I use phongap build - in my config.xml I have
`<preference name="android-targetSdkVersion" value="22" />` - seems to work 
`<preference name="android-targetSdkVersion" value="23" />` - does not work

Features / Permissions
`<feature name="http://api.phonegap.com/1.0/camera"/>`

Plugins
`<gap:plugin name="cordova-plugin-barcodescanner" source="npm" />`

I think I will try this plugin 'phonegap-plugin-barcodescanner' - [[github]](https://github.com/phonegap/phonegap-plugin-barcodescanner) [[npm]](https://www.npmjs.com/package/phonegap-plugin-barcodescanner)

**Comment by bpocallaghan** [comment]
Hi Akash.

Just wanted to let you know 'phonegap-plugin-barcodescanner'  - [[github]](https://github.com/phonegap/phonegap-plugin-barcodescanner) [[npm]](https://www.npmjs.com/package/phonegap-plugin-barcodescanner) works on latest android! :)

Please let me know if you have any issues...

**Comment by akashs1706** [comment]
@bpocallaghan Thanks for suggestions. I just installed Phonegap barcodescanner plugin. will let you know after testing it on some latest android versions.
Thanks.

**Comment by hypery2k** [comment]
could you try
```
cordova plugin add cordova-plugin-barcodescanner@next
```
?

**Comment by eurigilberto** [comment]
I tried using "cordova plugin add cordova-plugin-barcodescanner@next" but when I build the app, I cannot install it on my device.

**Comment by sam2996** [comment]
To solve this problem, you can give 'Camera permission'
