### ISSUE TITLE
Browser support.

### ISSUE THREAD

**Issue by fartwhif** [hypery2k/cordova-barcodescanner-plugin#43]
I've integrated QuaggaJS with cordova-barcodescanner-plugin for browser support of many barcode types (but not QR) and it works well.  It's a WebRTC based "extension to ZXing" and "not yet another port of ZXing".  It reads codes at weird angles!  I've also integrated jsqrcode-edi9999 for WebRTC based QR code support and the browser platform, which is under [Apache License 2.0](https://github.com/edi9999/jsqrcode/blob/master/COPYING).

The QuaggaJS license is [MIT](https://github.com/serratus/quaggaJS/blob/master/LICENSE)

What are the chances of having integrations like these added to the official cordova-barcodescanner-plugin so that it has support for browser platform instead of only a stub?  I would like to be able to use the official plugin for hybrid applications.

**Comment by hypery2k** [comment]
from my side no chance as i gave up the development of this plugin

**Comment by fartwhif** [comment]
Well that's good to know, thanks!
