### ISSUE TITLE
Text Box not Updating From the Result

### ISSUE THREAD

**Issue by fihamzuher** [hypery2k/cordova-barcodescanner-plugin#44]
Scan Result Not Updating the View.

`<label class="item item-input"><input type="text" id="txtNo" placeholder="Slip No" ng-model="Selected.barcode" />
                        </label>`

Inside a Function, i call this but it's not getting update 

`cordova.plugins.barcodeScanner.scan(
				      function (result) {
				      	$scope.Selected.barcode =  result.text;
					  },
				      function (error) {
				          alert("Scanning failed: " + error);
				      }
		         );`

$scope.Selected.barcode get the result text value but don't update the view. It will update  when do the second scan time. Please help. I have used without the plugin it's work perfectly , but when i try to update in barcodeScanner success it's not working.

**Comment by hypery2k** [comment]
you have to call $scope.$apply() to trigger the angular change detection. It‘s more an angular issue than a plugin issue.
BTW: The plugin is discontinued

**Comment by fihamzuher** [comment]
Thank you.

Best regards,
Fiham Zuher
------------------------------------------
Tel: +94716203710 | Email: fihamzuher@gmail.com
Colombo , Sri Lanka

<https://lk.linkedin.com/pub/fiham-zuher/8b/31b/754>

**Comment by fihamzuher** [comment]
Thank You
